AWSTemplateFormatVersion: '2010-09-09'
Description: s3 static web hosting stack
Parameters:
  PublicBucket:
    Description: public s3 bucket name
    Type: String
  HostedZoneName:
    Description: hosted zone name
    Type: String
  HostedZoneId:
    #https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_website_region_endpoints
    Description: hosted zone id
    Type: String
  WebsiteEndpoint:
    Description: website endpoint
    Type: String
  RecordName:
    Description: Record name
    Type: String
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref 'PublicBucket'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref "S3Bucket"
      PolicyDocument:
        Statement:
          - Action: ['s3:Get*']
            Effect: Allow
            Principal: "*"
            Resource:
            - !Join ['', ['arn:aws:s3:::', !Ref 'S3Bucket', /*]]
          - Action: ['s3:List*']
            Effect: Allow
            Principal: "*"
            Resource:
            - !Join ['', ['arn:aws:s3:::', !Ref 'S3Bucket']]

  StaticWebRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Type: A
      HostedZoneName: !Join ['', [!Ref 'HostedZoneName', '.']]
      Name: !Join ['', [!Ref 'RecordName', '.', !Ref 'HostedZoneName', '.']]
      AliasTarget:
        DNSName: !Ref 'WebsiteEndpoint'
        EvaluateTargetHealth: True
        HostedZoneId: !Ref 'HostedZoneId'
Outputs:
  WebsiteURL:
    Value: !GetAtt [S3Bucket, WebsiteURL]
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join ['', ['https://', !GetAtt [S3Bucket, DomainName]]]
    Description: Name of S3 bucket to hold website content
